export const PLANS = {
  solo: {
    name: "Solo",
    price: 149,
    monthlyPriceId: process.env.STRIPE_SOLO_PRICE_ID ?? "",
    annualPriceId: process.env.STRIPE_SOLO_ANNUAL_PRICE_ID ?? "",
    seats: 1,
    monthlyGenerationLimit: 100,
    description: "For solo practitioners",
    hasAgent: false,
    hasClientPortal: false,
    hasTridEngine: false,
    hasWireFraudMemory: false,
  },
  small_firm: {
    name: "Small Firm",
    price: 349,
    monthlyPriceId: process.env.STRIPE_SMALL_FIRM_PRICE_ID ?? "",
    annualPriceId: process.env.STRIPE_SMALL_FIRM_ANNUAL_PRICE_ID ?? "",
    seats: 5,
    monthlyGenerationLimit: 500,
    description: "Up to 5 attorneys",
    hasAgent: false,
    hasClientPortal: true,
    hasTridEngine: false,
    hasWireFraudMemory: true,
  },
  pro: {
    name: "Pro",
    price: 599,
    monthlyPriceId: process.env.STRIPE_PRO_PRICE_ID ?? "",
    annualPriceId: process.env.STRIPE_PRO_ANNUAL_PRICE_ID ?? "",
    seats: 10,
    monthlyGenerationLimit: 1500,
    description: "Full platform with AI agent",
    hasAgent: true,
    hasClientPortal: true,
    hasTridEngine: true,
    hasWireFraudMemory: true,
  },
  enterprise: {
    name: "Enterprise",
    price: 999,
    monthlyPriceId: process.env.STRIPE_ENTERPRISE_PRICE_ID ?? "",
    annualPriceId: process.env.STRIPE_ENTERPRISE_ANNUAL_PRICE_ID ?? "",
    seats: 25,
    monthlyGenerationLimit: 5000,
    description: "Unlimited power for large firms",
    hasAgent: true,
    hasClientPortal: true,
    hasTridEngine: true,
    hasWireFraudMemory: true,
  },
} as const

export type PlanKey = keyof typeof PLANS
